#!/bin/sh
# Remove what the ASSEMBLY left in the root, and prove none of it survived.
#
# Called from os/rootfs/stages/90-pack.Dockerfile (pack stage), where the reasoning lives.
#
# Two members so far, and they are the same kind of thing: a file that exists
# because this root was built by a package manager inside a container, and that
# means nothing -- or the wrong thing -- on a device. Neither can belong to a
# package: one is generated by another package's postinst and one arrives with
# the base image, so no producer in this repository could own either. That is
# what makes them the finalizer's, and it is the ruling
# os/rootfs/packages-src/system/Dockerfile already records for the first of them.
#
# EACH COUNT IS PRINTED. The two assembly paths reach this file with different
# residue -- the chain removes its own host keys in stages/10-base and never
# writes a policy-rc.d, the composer writes a policy-rc.d and removes it and
# never removes the host keys openssh-server's postinst generates -- so on each
# path one of these numbers is a real removal and the other is a tripwire. A
# silent step could be vacuous on both and read the same.

set -eu

# 1. sshd host keys. openssh-server's postinst generates a set at install time,
# and on a signed rootfs that is one private key the whole fleet shares. It is
# also random, so it would make the dm-verity root hash differ on every cold
# build. mos-seed-state generates a per-device set into STATE instead (see
# overlay-v2/usr/lib/mos/mos-seed-state).
keys_before="$(find /rootfs/etc/ssh -maxdepth 1 -name 'ssh_host_*' 2>/dev/null | wc -l)"
rm -f /rootfs/etc/ssh/ssh_host_*
keys_after="$(find /rootfs/etc/ssh -maxdepth 1 -name 'ssh_host_*' 2>/dev/null | wc -l)"
[ "${keys_after}" -eq 0 ] ||
    { echo "error: ${keys_after} sshd host key file(s) are still in /etc/ssh after the removal. A signed rootfs is byte-identical on every device, so a host key baked into one is a private key the whole fleet shares" >&2; exit 1; }

# 2. policy-rc.d. This one is NOT ours and never was: the Debian docker image
# ships /usr/sbin/policy-rc.d saying "For most Docker users, apt-get install
# only happens during docker build, where starting services doesn't work", and
# it is the reason a maintainer script cannot start a daemon during assembly.
# On a device it is a file that makes every invoke-rc.d refuse, for a reason
# that stopped applying the moment the image was packed.
#
# Found by the dual-build gate rather than by reading: the chain ships the base
# image's copy, the composer removes the one it wrote and takes the base
# image's with it, and the comparison reported /usr/sbin/policy-rc.d as a path
# present on one side only. Removing it here is what gives the two paths one
# answer, and the answer is the correct one for both.
rc_before="$(find /rootfs/usr/sbin -maxdepth 1 -name 'policy-rc.d' 2>/dev/null | wc -l)"
rm -f /rootfs/usr/sbin/policy-rc.d
[ ! -e /rootfs/usr/sbin/policy-rc.d ] ||
    { echo "error: /usr/sbin/policy-rc.d is still in the packed root. It answers 101 to every invoke-rc.d, so a device carrying it refuses to start any service through that path" >&2; exit 1; }

echo "residue: ${keys_before} sshd host key file(s) and ${rc_before} policy-rc.d removed from the packed root"
