#!/bin/sh
# Remove what the ASSEMBLY left in the root, and prove none of it survived.
#
# Called from os/rootfs/compose/90-pack.Dockerfile (pack stage), where the reasoning lives.
#
# Three members so far, and they are the same kind of thing: something that
# exists because this root was built by a package manager inside a container,
# and that means nothing -- or the wrong thing -- on a device. None can belong
# to a package: one is generated by another package's postinst, one arrives with
# the base image, and one is created by RUNNING a container during assembly. So
# no producer in this repository could own any of them, which is what makes them
# the finalizer's, and it is the ruling
# os/rootfs/packages-src/system/Dockerfile already records for the first.
#
# EACH COUNT IS PRINTED. The composition writes a policy-rc.d and removes it
# again, and never removes the host keys openssh-server's postinst generates --
# so one of these numbers is a real removal and the other is a tripwire, and
# which is which is not the same on every root this file is asked to close. A
# silent step could be vacuous and read exactly like a working one.

set -eu

# 1. sshd host keys. openssh-server's postinst generates a set at install time,
# and on a signed rootfs that is one private key the whole fleet shares. It is
# also random, so it would make the dm-verity root hash differ on every cold
# build. mos-seed-state generates a per-device set into STATE instead (see
# overlay/usr/lib/mos/mos-seed-state).
keys_before="$(find /rootfs/etc/ssh -maxdepth 1 -name 'ssh_host_*' 2>/dev/null | wc -l)"
rm -f /rootfs/etc/ssh/ssh_host_*
keys_after="$(find /rootfs/etc/ssh -maxdepth 1 -name 'ssh_host_*' 2>/dev/null | wc -l)"
[ "${keys_after}" -eq 0 ] ||
    { echo "error: ${keys_after} sshd host key file(s) are still in /etc/ssh after the removal. A signed rootfs is byte-identical on every device, so a host key baked into one is a private key the whole fleet shares" >&2; exit 1; }

# 2. policy-rc.d. This one is NOT ours and never was: the Debian docker image
# ships /usr/sbin/policy-rc.d saying "For most Docker users, apt-get install
# only happens during docker build, where starting services doesn't work", and
# it is the reason a maintainer script cannot start a daemon during assembly.
# On a device it is a file that makes every invoke-rc.d refuse, for a reason
# that stopped applying the moment the image was packed.
#
# Found by the dual-build gate rather than by reading: the chain ships the base
# image's copy, the composer removes the one it wrote and takes the base
# image's with it, and the comparison reported /usr/sbin/policy-rc.d as a path
# present on one side only. Removing it here is what gives the two paths one
# answer, and the answer is the correct one for both.
rc_before="$(find /rootfs/usr/sbin -maxdepth 1 -name 'policy-rc.d' 2>/dev/null | wc -l)"
rm -f /rootfs/usr/sbin/policy-rc.d
[ ! -e /rootfs/usr/sbin/policy-rc.d ] ||
    { echo "error: /usr/sbin/policy-rc.d is still in the packed root. It answers 101 to every invoke-rc.d, so a device carrying it refuses to start any service through that path" >&2; exit 1; }

# 3. The container engine's runtime state, left by EXERCISING it during
# assembly: running a container makes crun create its state directory at
# /run/crun. The composition never runs one, so this is a tripwire on the root
# it closes today rather than a removal. Kept because the removal is cheap and
# the state is unmistakably build residue if it ever appears.
#
# /run IS A TMPFS AT RUNTIME, so nothing under it in the image is ever read.
# That argues for emptying the directory wholesale, and this deliberately does
# NOT: /run in the packed root holds 21 other entries -- /run/lock, /run/shm,
# /run/user, the systemd tree, and the stub-resolv.conf that /etc/resolv.conf
# points at -- every one of them identical on both paths and put there by the
# base image or by a package postinst. Removing them would be a change to the
# shipped chain image that nothing in the verifier has ever asserted, made in
# passing by a step whose subject is build residue. Enumerated rather than
# assumed: the two roots hold 22 and 21 paths under /run and differ in exactly
# this one.
#
# No membership test is available here, unlike the package-manager purge's:
# dpkg owns none of /run on either path, so "no package owns it" would sweep the
# base image's directories too. The tripwire for a SECOND member is the
# dual-build gate itself, which compares /run like every other path and would
# report a new one the same way it reported this.
run_before="$(find /rootfs/run -maxdepth 1 -name 'crun' 2>/dev/null | wc -l)"
rm -rf /rootfs/run/crun
[ ! -e /rootfs/run/crun ] ||
    { echo "error: /run/crun is still in the packed root after the removal" >&2; exit 1; }

echo "residue: ${keys_before} sshd host key file(s), ${rc_before} policy-rc.d and ${run_before} container-runtime state dir(s) removed from the packed root"
echo "residue: /run holds $(find /rootfs/run -mindepth 1 | wc -l) path(s), none of them this build's"
