//! End-to-end tests for the online-key rotation ceremony: the recovery that
//! revokes the release host's `targets`, `snapshot` and `timestamp` keys by
//! publishing a new root version that binds fresh ones.
//!
//! Shaped like `rotation.rs` and for the same reason: what is being tested is
//! not a signer feature but a fleet property — that a device pinned to the
//! existing anchor follows the repository across the rotation, and that
//! metadata signed by the revoked keys is refused by exactly the clients the
//! revocation exists to protect. Both halves of each scenario sit in one test.
//!
//! Same isolation as the other suites (see `common/mod.rs`): everything in a
//! `TempDir`, keys generated by the test and thrown away with it, no network.

mod common;

use std::fs;
use std::num::NonZeroU64;

use common::{Fixture, at, read_json, root_expiry, valid_expirations};
use rauc_sign::client;
use rauc_sign::keys;
use rauc_sign::repo;
use ring::rand::SystemRandom;
use tough::editor::signed::SignedRole;
use tough::schema::{KeyHolder, Root, Signed, Timestamp};

/// Generates the incoming online keys the way the ceremony does: the three
/// online roles and nothing else — no spare copy of the root key on media
/// that goes to the release host.
fn new_online_keys(fx: &Fixture, name: &str) -> std::path::PathBuf {
    let dir = fx.scratch(name);
    keys::generate_roles(&dir, &keys::ONLINE_ROLES).expect("generate the incoming online keys");
    dir
}

/// One role's key id list, as the given root document binds it.
fn role_keyids(root: &serde_json::Value, role: &str) -> Vec<String> {
    root["signed"]["roles"][role]["keyids"]
        .as_array()
        .expect("role keyids")
        .iter()
        .map(|id| id.as_str().expect("keyid string").to_string())
        .collect()
}

/// The rotation carries the fleet forward: a device pinned to the original
/// anchor walks to the new root, and the re-signed repository — targets
/// carried, every online version bumped — verifies end to end.
#[tokio::test]
async fn online_rotation_revokes_the_old_keys_and_keeps_the_anchor() {
    let fx = Fixture::new().await;
    let incoming = new_online_keys(&fx, "incoming-online-keys");

    let version = repo::rotate_online_keys(
        &fx.repo,
        &fx.keys_dir,
        &incoming,
        root_expiry(),
        valid_expirations(),
    )
    .await
    .expect("rotate the online keys");
    assert_eq!(version, 2);

    let before = read_json(&fx.trusted_root);
    let after = read_json(&repo::metadata_dir(&fx.repo).join("2.root.json"));

    // The trust anchor did not change hands: the root role names the same key,
    // and its single signature is all the ceremony needs.
    assert_eq!(role_keyids(&after, "root"), role_keyids(&before, "root"));
    assert_eq!(
        after["signatures"].as_array().map(Vec::len),
        Some(1),
        "an online rotation is signed once, by the unchanged root key"
    );

    // Every online role changed hands, and the outgoing keys are revoked, not
    // merely superseded: no role lists them and the key map does not carry them.
    for role in ["targets", "snapshot", "timestamp"] {
        let old = role_keyids(&before, role);
        let new = role_keyids(&after, role);
        assert_ne!(old, new, "the {role} key must have changed");
        for id in &old {
            assert!(
                after["signed"]["keys"][id].is_null(),
                "the outgoing {role} key must not remain listed in the new root"
            );
        }
    }

    // A device pinned to the original anchor follows: root v2, every online
    // role bumped past the fixture's v2, the published release still visible
    // and its bytes still verifiable.
    let state = fx.scratch("state.json");
    let report = client::verify_repository(&fx.repo, &fx.trusted_root, &state)
        .await
        .expect("the original anchor must reach the rotated repository");
    assert_eq!(report.root_version, 2);
    assert_eq!(report.targets_version, 3);
    assert_eq!(report.snapshot_version, 3);
    assert_eq!(report.timestamp_version, 3);
    assert_eq!(report.targets, vec!["update-1.0.0.raucb".to_string()]);

    let path = client::verify_target(&fx.repo, &fx.trusted_root, &state, "update-1.0.0.raucb")
        .await
        .expect("the carried target must still verify");
    assert_eq!(
        fs::read(&path).expect("read verified path"),
        fs::read(&fx.bundle).expect("read original bundle"),
        "the carried target must still hold the published bytes"
    );

    // And what the release host does next: publishing with the INCOMING keys
    // works, so the rotation did not cost the repository its ability to release.
    repo::add(
        &fx.repo,
        &incoming,
        &fx.bundle,
        Some("update-1.1.0.raucb"),
        common::VERITY_ROOT_HASH,
        Some("1.1.0"),
        valid_expirations(),
    )
    .await
    .expect("publish a release after the rotation with the incoming keys");
    let report = client::verify_repository(&fx.repo, &fx.trusted_root, &state)
        .await
        .expect("the post-rotation release must verify");
    assert!(
        report.targets.contains(&"update-1.1.0.raucb".to_string()),
        "the release published after the rotation must be visible: {:?}",
        report.targets
    );
}

/// The point of the ceremony, from the attacker's side: the revoked keys can
/// sign nothing a client accepts any more — and the signer refuses to even try
/// with them, because the new root no longer names their key ids.
#[tokio::test]
async fn metadata_signed_by_revoked_online_keys_is_refused() {
    let fx = Fixture::new().await;
    let incoming = new_online_keys(&fx, "incoming-online-keys");
    repo::rotate_online_keys(
        &fx.repo,
        &fx.keys_dir,
        &incoming,
        root_expiry(),
        valid_expirations(),
    )
    .await
    .expect("rotate the online keys");

    let state = fx.scratch("state.json");
    client::verify_repository(&fx.repo, &fx.trusted_root, &state)
        .await
        .expect("verify the rotated repository");

    // Signer side: the release host still holding the outgoing keys cannot
    // publish — the new root lists no key id its keys match.
    let err = repo::resign(
        &fx.repo,
        &fx.keys_dir,
        None,
        None,
        false,
        valid_expirations(),
    )
    .await
    .expect_err("re-signing with the revoked online keys must be refused");
    assert!(
        format!("{err:#}").contains("Unable to match any of the provided keys"),
        "error should say the keys are not the ones the root names: {err:#}"
    );

    // Client side: a timestamp the attacker hand-signs with the revoked key —
    // internally well-formed, listed under the OLD root — is refused by a
    // client that has walked to the new one.
    let meta = repo::metadata_dir(&fx.repo);
    let old_root: Signed<Root> =
        serde_json::from_slice(&fs::read(&fx.trusted_root).expect("read old anchor"))
            .expect("parse old anchor");
    let mut timestamp: Signed<Timestamp> =
        serde_json::from_slice(&fs::read(meta.join("timestamp.json")).expect("read timestamp"))
            .expect("parse timestamp");
    timestamp.signed.version = NonZeroU64::new(4).expect("nonzero");
    // Far-future expiry, so the refusal below is the revoked key and nothing else.
    timestamp.signed.expires = at("2099-01-01T00:00:00Z");
    let old_key = keys::sources(&fx.keys_dir, &["timestamp"]).expect("revoked timestamp key");
    let forged = SignedRole::new(
        timestamp.signed,
        &KeyHolder::Root(old_root.signed),
        &old_key,
        &SystemRandom::new(),
    )
    .await
    .expect("sign the forged timestamp with the revoked key");
    fs::write(meta.join("timestamp.json"), forged.buffer()).expect("publish the forgery");

    let err = client::verify_repository(&fx.repo, &fx.trusted_root, &state)
        .await
        .expect_err("a timestamp signed by a revoked key must be refused");
    assert!(
        format!("{err:#}").contains("threshold"),
        "error should report the unmet timestamp threshold: {err:#}"
    );
}

/// Rotating "to" a key the root already trusts is not a rotation — the
/// outgoing key would survive its own revocation. Refused before anything is
/// written, naming the role.
#[tokio::test]
async fn rotating_online_keys_to_an_incumbent_key_is_refused() {
    let fx = Fixture::new().await;

    let err = repo::rotate_online_keys(
        &fx.repo,
        &fx.keys_dir,
        &fx.keys_dir,
        root_expiry(),
        valid_expirations(),
    )
    .await
    .expect_err("rotating to the incumbent online keys must be refused");
    assert!(
        format!("{err:#}").contains("already holding the role"),
        "error should say the key already holds the role: {err:#}"
    );
    assert!(
        !repo::metadata_dir(&fx.repo).join("2.root.json").exists(),
        "the refusal must not have published anything"
    );

    // And the repository is untouched: the fixture still verifies as published.
    let report = client::verify_repository(&fx.repo, &fx.trusted_root, &fx.scratch("state.json"))
        .await
        .expect("the repository must be untouched after the refusal");
    assert_eq!(report.root_version, 1);
    assert_eq!(report.timestamp_version, 2);
}
