//! End-to-end tests for the two root ceremonies: the rotation that hands the
//! root role to a new key, and the annual refresh that re-signs it with the
//! same one.
//!
//! Not split along the signer/device line the other two suites follow
//! (`repository.rs`, `client.rs`), because a rotation is not a signer feature
//! that a client happens to tolerate: the property being tested is that a
//! device pinned to the OUTGOING anchor walks itself to the incoming one, and
//! the signer half alone proves nothing about it. Both halves of each scenario
//! therefore sit in one test.
//!
//! Same isolation as the other suites (see `common/mod.rs`): everything in a
//! `TempDir`, keys generated by the test and thrown away with it, no network.

mod common;

use std::fs;

use common::{Fixture, VERITY_ROOT_HASH, at, read_json, root_expiry, valid_expirations};
use rauc_sign::client;
use rauc_sign::keys;
use rauc_sign::repo;
use ring::rand::SystemRandom;
use serde_json::Value;
use tough::editor::signed::SignedRole;
use tough::schema::{KeyHolder, Root, Signed};

/// Generates the incoming root key on its own, the way a rotation ceremony
/// does: one new offline key, no spare copies of the online keys.
fn new_root_key(fx: &Fixture, name: &str) -> std::path::PathBuf {
    let dir = fx.scratch(name);
    keys::generate_roles(&dir, &["root"]).expect("generate the incoming root key");
    dir
}

/// The root role's single key id, as the given root document lists it.
fn root_keyid(root: &Value) -> String {
    let ids = root["signed"]["roles"]["root"]["keyids"]
        .as_array()
        .expect("root keyids");
    assert_eq!(ids.len(), 1, "this tool binds one key per role");
    ids[0].as_str().expect("keyid string").to_string()
}

/// Publishes the rotated root out of band, as §1.5 requires of any anchor: a
/// copy taken OUT of the repository, never a `--root` pointed back into it.
fn distribute(fx: &Fixture, version: u64, name: &str) -> std::path::PathBuf {
    let out = fx.scratch(name);
    fs::copy(
        repo::metadata_dir(&fx.repo).join(format!("{version}.root.json")),
        &out,
    )
    .expect("distribute the new trust anchor");
    out
}

/// The overlap window, in the direction that matters: a device still pinned to
/// the anchor from the first ceremony reaches the rotated root by itself, with
/// nothing shipped to it but the repository.
#[tokio::test]
async fn rotation_is_accepted_from_the_outgoing_anchor() {
    let fx = Fixture::new().await;
    let incoming = new_root_key(&fx, "incoming-keys");

    let version = repo::rotate_root(&fx.repo, &fx.keys_dir, Some(&incoming), root_expiry())
        .await
        .expect("rotate the root key");
    assert_eq!(version, 2);

    let report = client::verify_repository(&fx.repo, &fx.trusted_root, &fx.scratch("state.json"))
        .await
        .expect("the outgoing anchor must reach the rotated root");
    assert_eq!(report.root_version, 2);

    let outgoing_id = root_keyid(&read_json(&fx.trusted_root));
    let rotated = read_json(&repo::metadata_dir(&fx.repo).join("2.root.json"));

    // The cross-sign is what made the walk above possible: both keys signed.
    let signatures = rotated["signatures"].as_array().expect("signatures");
    assert_eq!(signatures.len(), 2, "a rotation carries two signatures");
    assert!(
        signatures
            .iter()
            .any(|s| s["keyid"].as_str() == Some(outgoing_id.as_str())),
        "the outgoing key must have signed the document that replaces it"
    );

    // And the outgoing key is revoked, not merely superseded: it holds no role
    // and is not listed among the trusted keys at all.
    assert_ne!(root_keyid(&rotated), outgoing_id);
    assert!(
        rotated["signed"]["keys"][&outgoing_id].is_null(),
        "the outgoing root key must not remain listed in the new anchor"
    );
}

/// The other direction, plus what the release host does next: a device pinned
/// to the NEW anchor verifies, and releases published after the ceremony with
/// the unchanged online keys verify from either anchor. Rotating root must not
/// cost the repository its ability to publish.
#[tokio::test]
async fn releases_after_a_rotation_verify_from_either_anchor() {
    let fx = Fixture::new().await;
    let incoming = new_root_key(&fx, "incoming-keys");
    repo::rotate_root(&fx.repo, &fx.keys_dir, Some(&incoming), root_expiry())
        .await
        .expect("rotate the root key");
    let new_anchor = distribute(&fx, 2, "trusted-root-2.json");

    repo::add(
        &fx.repo,
        &fx.keys_dir,
        &fx.bundle,
        Some("update-1.1.0.raucb"),
        VERITY_ROOT_HASH,
        Some("1.1.0"),
        valid_expirations(),
    )
    .await
    .expect("publish a release after the rotation with the online keys");

    for (anchor, state) in [
        (&fx.trusted_root, "state-old.json"),
        (&new_anchor, "state-new.json"),
    ] {
        let report = client::verify_repository(&fx.repo, anchor, &fx.scratch(state))
            .await
            .expect("both anchors verify the post-rotation repository");
        assert_eq!(report.root_version, 2);
        assert!(
            report.targets.contains(&"update-1.1.0.raucb".to_string()),
            "the release published after the rotation must be visible: {:?}",
            report.targets
        );
    }
}

/// The annual refresh: a new version and a new expiration over the SAME key.
/// The anchor does not change hands, so there is nothing to redistribute — and
/// the document proves it by naming the same key id it did before.
#[tokio::test]
async fn refresh_extends_the_expiry_without_changing_the_anchor() {
    let fx = Fixture::new().await;
    let renewed = at("2100-01-01T00:00:00Z");

    let version = repo::rotate_root(&fx.repo, &fx.keys_dir, None, renewed)
        .await
        .expect("refresh the root at its expiry");
    assert_eq!(version, 2);

    let before = read_json(&fx.trusted_root);
    let after = read_json(&repo::metadata_dir(&fx.repo).join("2.root.json"));
    assert_eq!(root_keyid(&after), root_keyid(&before));
    assert_eq!(
        at(after["signed"]["expires"].as_str().expect("expires")),
        renewed
    );
    // One key holds the role before and after, so the cross-sign is satisfied
    // by one signature. That degeneracy is the difference between the two
    // ceremonies, stated as an assertion.
    assert_eq!(
        after["signatures"].as_array().map(Vec::len),
        Some(1),
        "a refresh is signed once, by the key that already held the role"
    );

    let report = client::verify_repository(&fx.repo, &fx.trusted_root, &fx.scratch("state.json"))
        .await
        .expect("the unchanged anchor must accept the refreshed root");
    assert_eq!(report.root_version, 2);
}

/// The point of the cross-sign, isolated: a rotated root signed by the incoming
/// key ALONE is internally consistent — a threshold of its own root keys signed
/// it — and a client pinned to the new anchor accepts it. A client pinned to
/// the outgoing anchor must not, because nothing in that document ties it to
/// the key the device already trusts.
#[tokio::test]
async fn a_rotation_the_outgoing_key_did_not_sign_is_refused() {
    let fx = Fixture::new().await;
    let incoming = new_root_key(&fx, "incoming-keys");
    repo::rotate_root(&fx.repo, &fx.keys_dir, Some(&incoming), root_expiry())
        .await
        .expect("rotate the root key");

    // Re-sign the very same rotated document with the incoming key alone.
    let meta = repo::metadata_dir(&fx.repo);
    let rotated: Signed<Root> =
        serde_json::from_slice(&fs::read(meta.join("2.root.json")).expect("read rotated root"))
            .expect("parse rotated root");
    let holder = KeyHolder::Root(rotated.signed.clone());
    let incoming_only = keys::sources(&incoming, &["root"]).expect("incoming key source");
    let resigned = SignedRole::new(
        rotated.signed,
        &holder,
        &incoming_only,
        &SystemRandom::new(),
    )
    .await
    .expect("sign the rotation with the incoming key alone");
    assert_eq!(resigned.signed().signatures.len(), 1);
    fs::write(meta.join("2.root.json"), resigned.buffer()).expect("republish");
    fs::write(meta.join("root.json"), resigned.buffer()).expect("republish the alias");

    let err = client::verify_repository(&fx.repo, &fx.trusted_root, &fx.scratch("state.json"))
        .await
        .expect_err("a rotation the outgoing key did not sign must be refused");
    let rendered = format!("{err:#}");
    assert!(
        rendered.contains("Signature threshold of 1 not met for role root"),
        "error should report the unmet root threshold: {rendered}"
    );

    // Same bytes, accepted by a client pinned to the new anchor. Self-
    // consistency is not the property the outgoing anchor is checking.
    let new_anchor = distribute(&fx, 2, "trusted-root-2.json");
    let report = client::verify_repository(&fx.repo, &new_anchor, &fx.scratch("state-new.json"))
        .await
        .expect("the new anchor accepts its own root");
    assert_eq!(report.root_version, 2);
}

/// A rotation whose outgoing signature does not verify is refused. The document
/// still carries two signatures and still names both keys; only the bytes of
/// the one that matters to a device on the old anchor are wrong.
#[tokio::test]
async fn a_rotated_root_with_a_broken_outgoing_signature_is_refused() {
    let fx = Fixture::new().await;
    let incoming = new_root_key(&fx, "incoming-keys");
    repo::rotate_root(&fx.repo, &fx.keys_dir, Some(&incoming), root_expiry())
        .await
        .expect("rotate the root key");

    let outgoing_id = root_keyid(&read_json(&fx.trusted_root));
    let meta = repo::metadata_dir(&fx.repo);
    let path = meta.join("2.root.json");
    let mut rotated = read_json(&path);

    // Control: this test rewrites the file through serde_json, which reorders
    // JSON object members. Verification canonicalises before checking, so that
    // must not matter -- and the refusal below must be the flipped signature
    // rather than the round trip. Proved here rather than assumed.
    let round_tripped = serde_json::to_vec_pretty(&rotated).expect("serialize");
    fs::write(&path, &round_tripped).expect("write");
    fs::write(meta.join("root.json"), &round_tripped).expect("write the alias");
    client::verify_repository(
        &fx.repo,
        &fx.trusted_root,
        &fx.scratch("state-control.json"),
    )
    .await
    .expect("a round-tripped rotation must still verify");

    let signature = rotated["signatures"]
        .as_array_mut()
        .expect("signatures")
        .iter_mut()
        .find(|s| s["keyid"].as_str() == Some(outgoing_id.as_str()))
        .expect("the outgoing key's signature");
    // Stays valid hex, so this fails as a signature and not as a parse.
    let sig = signature["sig"].as_str().expect("sig").to_string();
    let flipped = format!(
        "{}{}",
        if sig.starts_with('0') { '1' } else { '0' },
        &sig[1..]
    );
    signature["sig"] = Value::String(flipped);
    let edited = serde_json::to_vec_pretty(&rotated).expect("serialize");
    fs::write(&path, &edited).expect("write");
    fs::write(meta.join("root.json"), &edited).expect("write the alias");

    let err = client::verify_repository(&fx.repo, &fx.trusted_root, &fx.scratch("state.json"))
        .await
        .expect_err("a rotation with a broken outgoing signature must be refused");
    let rendered = format!("{err:#}");
    assert!(
        rendered.contains("Signature threshold of 1 not met for role root"),
        "error should report the unmet root threshold: {rendered}"
    );
}

/// Withdrawing a published rotation is a root rollback: every signature in what
/// remains is still valid, and only the device's own memory says the repository
/// has gone backwards. That memory is the state file, so the refusal survives a
/// restart.
#[tokio::test]
async fn a_root_rollback_is_refused_across_restarts() {
    let fx = Fixture::new().await;
    let incoming = new_root_key(&fx, "incoming-keys");
    repo::rotate_root(&fx.repo, &fx.keys_dir, Some(&incoming), root_expiry())
        .await
        .expect("rotate the root key");

    let state = fx.scratch("state.json");
    let report = client::verify_repository(&fx.repo, &fx.trusted_root, &state)
        .await
        .expect("verify the rotated repository");
    assert_eq!(report.root_version, 2);
    assert_eq!(read_json(&state)["root"].as_u64(), Some(2));

    // The repository is served again from before the ceremony.
    let meta = repo::metadata_dir(&fx.repo);
    fs::remove_file(meta.join("2.root.json")).expect("withdraw the rotated root");
    fs::copy(meta.join("1.root.json"), meta.join("root.json")).expect("restore the old alias");

    let err = client::verify_repository(&fx.repo, &fx.trusted_root, &state)
        .await
        .expect_err("a withdrawn rotation must be refused");
    let rendered = format!("{err:#}");
    assert!(
        rendered.contains("root version 1 is below the previously verified version 2"),
        "error should name the role and the remembered version: {rendered}"
    );
    assert_eq!(
        read_json(&state)["root"].as_u64(),
        Some(2),
        "a rejection must not advance the remembered version"
    );
}

/// The likeliest mistake in the room: the operator carries the wrong sealed
/// media, so `--keys-dir` holds a root key that does not hold the role. Nothing
/// upstream of the write would notice — the document is signed, by a key, and is
/// self-consistent — and every deployed device would then refuse it. The
/// pre-write check against the OUTGOING root is what turns that into a refusal
/// on the offline machine, while the ceremony is still in session.
#[tokio::test]
async fn rotating_with_the_wrong_outgoing_key_is_refused() {
    let fx = Fixture::new().await;
    let wrong = new_root_key(&fx, "wrong-outgoing-keys");
    let incoming = new_root_key(&fx, "incoming-keys");

    let err = repo::rotate_root(&fx.repo, &wrong, Some(&incoming), root_expiry())
        .await
        .expect_err("a rotation the real outgoing key never signed must be refused");
    assert!(
        format!("{err:#}").contains("not signed by a threshold of the outgoing root keys"),
        "error should say which half of the cross-sign is missing: {err:#}"
    );
    assert!(
        !repo::metadata_dir(&fx.repo).join("2.root.json").exists(),
        "the refusal must not have published anything"
    );

    // The same mistake on the refresh path fails earlier and just as plainly,
    // because that ceremony has no second key to sign with.
    let err = repo::rotate_root(&fx.repo, &wrong, None, root_expiry())
        .await
        .expect_err("a refresh signed by a key the root does not name must be refused");
    assert!(
        format!("{err:#}").contains("Unable to match any of the provided keys with root.json"),
        "error should say the key is not the one the root names: {err:#}"
    );
}

/// Handing the role to the key that already holds it is the annual refresh
/// wearing a rotation's name. The two ceremonies differ in what they oblige an
/// operator to do afterwards — redistribute an anchor, or not — so this is
/// refused rather than quietly performed.
#[tokio::test]
async fn rotating_to_the_key_that_already_holds_the_role_is_refused() {
    let fx = Fixture::new().await;

    let err = repo::rotate_root(&fx.repo, &fx.keys_dir, Some(&fx.keys_dir), root_expiry())
        .await
        .expect_err("rotating to the incumbent key must be refused");
    let rendered = format!("{err:#}");
    assert!(
        rendered.contains("refresh-root"),
        "error should name the ceremony the operator meant: {rendered}"
    );
    assert!(
        !repo::metadata_dir(&fx.repo).join("2.root.json").exists(),
        "the refusal must not have published anything"
    );
}

/// A published root version is a file some device may already have walked to.
/// If the `root.json` alias is a stale copy of an older version — the shape a
/// partial media copy leaves behind — rotating again would overwrite a
/// published document with a different one under the same name.
#[tokio::test]
async fn rewriting_a_published_root_version_is_refused() {
    let fx = Fixture::new().await;
    let meta = repo::metadata_dir(&fx.repo);
    repo::rotate_root(
        &fx.repo,
        &fx.keys_dir,
        Some(&new_root_key(&fx, "incoming-keys")),
        root_expiry(),
    )
    .await
    .expect("rotate the root key");
    let published = fs::read(meta.join("2.root.json")).expect("read the published root");

    fs::copy(meta.join("1.root.json"), meta.join("root.json")).expect("leave a stale alias");
    let err = repo::rotate_root(
        &fx.repo,
        &fx.keys_dir,
        Some(&new_root_key(&fx, "incoming-keys-2")),
        root_expiry(),
    )
    .await
    .expect_err("overwriting a published root version must be refused");
    assert!(
        format!("{err:#}").contains("never rewritten"),
        "error should explain what it is protecting: {err:#}"
    );
    assert_eq!(
        fs::read(meta.join("2.root.json")).expect("read the published root"),
        published,
        "the published root version must be untouched"
    );
}

/// The anchor a ceremony rotates FROM is carried to the offline machine on
/// media. A copy its own keys do not sign is not the anchor the fleet is on,
/// and a chain rooted at it is one no deployed device can walk — a fact that
/// would otherwise surface only after the ceremony, with the key sealed away
/// again.
#[tokio::test]
async fn rotating_from_an_unsigned_anchor_is_refused() {
    let fx = Fixture::new().await;
    let path = repo::metadata_dir(&fx.repo).join("root.json");
    let mut root = read_json(&path);
    root["signed"]["expires"] = Value::String("2098-01-01T00:00:00Z".to_string());
    fs::write(&path, serde_json::to_vec_pretty(&root).expect("serialize")).expect("write");

    let err = repo::rotate_root(
        &fx.repo,
        &fx.keys_dir,
        Some(&new_root_key(&fx, "incoming-keys")),
        root_expiry(),
    )
    .await
    .expect_err("rotating from an unsigned anchor must be refused");
    assert!(
        format!("{err:#}").contains("is not signed by its own root keys"),
        "error should say the anchor itself did not verify: {err:#}"
    );
}

/// `--role` is operator input; a typo must not silently generate nothing and
/// leave the ceremony holding an empty directory.
#[tokio::test]
async fn generating_a_key_for_an_unknown_role_is_refused() {
    let fx = Fixture::new().await;
    let dir = fx.scratch("typo-keys");

    let err = keys::generate_roles(&dir, &["rooot"]).expect_err("unknown role must be refused");
    assert!(
        format!("{err:#}").contains("unknown role"),
        "error should name the problem: {err:#}"
    );
    assert!(!dir.exists(), "nothing must be created for a bad role name");
}
