ctrl_interface=/run/wpa_supplicant
update_config=1
country=US

# Wi-Fi demo. This entire example is commented out and will not connect.
#   wpa_passphrase 'DemoWiFi' 'ChangeMe1234'
# Example output:
# network={
#	ssid="DemoWiFi"
#	#psk="ChangeMe1234"
#	psk=2865d37bfe4035f2c5274b6831c4863ac29edbd3fcf554ea5b59483cd349960d
# }
#
# Run wpa_passphrase and append its network={} output to this file.
