[Unit]
Requires=systemd-repart.service
After=systemd-repart.service
[Service]
# ext4 requires CAP_SYS_RESOURCE to resize. Keep it only for this fixed helper.
CapabilityBoundingSet=
CapabilityBoundingSet=CAP_SYS_RESOURCE CAP_SYS_ADMIN CAP_DAC_OVERRIDE
TimeoutStartSec=30
