# RELEASE NAME: 20210721_BT_ANDROID_10.0
# Bluetooth Device Name
#Name=SeekWave Bluetooth

#Indicate USB/SDIO or UART driver bluetooth
BtDeviceNode=/dev/BTCMD
BtDeviceNode=/dev/BTDATA
BtDeviceNode=/dev/BTAUDIO
#BtDeviceNode=/dev/BTISOC
#BtDeviceNode=?/dev/ttyS0

# Enable BtSnoop logging function
# valid value : true, false
SkwBtUartOnly=false
#SkwBtNoSleep:just for uart mode
SkwBtNoSleep=false
SkwBtsnoopDump=false
SkwBtcplog=false
SkwBtDrvlog=false

####WakeupADVData=gpio No;effactive level;addr offset;ADVData;Mask  ### ADVData size must be equal Mask size
#WakeupADVData=16;1;0;020106031980010FFF00112233AABBCCDD;0000FF0000FFFFFF000000000000000000

# BtSnoop log output file
BtSnoopFileName=/var/lib/bluetooth/btsnoop_hci.cfa


# Preserve existing BtSnoop log before overwriting
BtSnoopSaveLog=false
SkwLogSlice=false
