# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32
# check=skip=InvalidDefaultArgInFrom
ARG MICA_BUN_IMAGE
ARG MICA_LAB_IMAGE
FROM ${MICA_BUN_IMAGE} AS bun
FROM ${MICA_LAB_IMAGE}
COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun
