# The DT describes the card, but all codecs and the card driver are modules.
modules=amlogic-snd-codec-dummy amlogic-snd-codec-t9015 amlogic-snd-soc
card=0
control-device=/dev/snd/controlC0
wait-seconds=10
source-control=HDMITX Audio Source Select
source-value=Tdm_B
format-control=Audio I2S to HDMITX Format
format-value=Stereo PCM
mask-control=Audio I2S to HDMITX Mask
mask-value=3
mute-control=Audio hdmi-out mute
mute-value=off
